name: golang-ci

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Test
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.52.0
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: golangci-lint
        run: golangci-lint run --modules-download-mode=mod
